
package unit8_ooplibrary;

import java.awt.BorderLayout;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author namphan
 */
public class LibraryGUI extends javax.swing.JFrame {
    private String intro = "You just listened to:\n\n";
    private String introBook = "You have selected:\n\n";
    /**
     * Creates new form LibraryGUI
     */
    public LibraryGUI() {
        this.initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libraryTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookTab = new javax.swing.JPanel();
        bookCover = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxt_DisplayBook = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        cdTab = new javax.swing.JPanel();
        cdCover = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxt_DisplayCD_DVD = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1012, 980));
        setPreferredSize(new java.awt.Dimension(680, 680));

        libraryTab.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        libraryTab.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Oriya MN", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("G1 LIBRARY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 292, 62);

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("WE HOPE YOU CAN FIND SOME LITTLE INTERESTING THINGS HERE.");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 430, 420, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/global.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 80, 419, 348);

        libraryTab.addTab("HOME", new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_HomeButton.png")), jPanel1, ""); // NOI18N

        bookTab.setBackground(new java.awt.Color(255, 204, 51));

        bookCover.setBackground(new java.awt.Color(204, 102, 0));

        jTxt_DisplayBook.setColumns(20);
        jTxt_DisplayBook.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jTxt_DisplayBook.setRows(5);
        jScrollPane2.setViewportView(jTxt_DisplayBook);

        javax.swing.GroupLayout bookCoverLayout = new javax.swing.GroupLayout(bookCover);
        bookCover.setLayout(bookCoverLayout);
        bookCoverLayout.setHorizontalGroup(
            bookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        bookCoverLayout.setVerticalGroup(
            bookCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookCoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Java - How to Program.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Juran's Quality Handbook.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lord Of The Rings.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("<< Select a Book");

        javax.swing.GroupLayout bookTabLayout = new javax.swing.GroupLayout(bookTab);
        bookTab.setLayout(bookTabLayout);
        bookTabLayout.setHorizontalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        bookTabLayout.setVerticalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookTabLayout.createSequentialGroup()
                .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookTabLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookTabLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        libraryTab.addTab("BOOK", new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_book.png")), bookTab); // NOI18N

        cdTab.setBackground(new java.awt.Color(255, 51, 51));

        cdCover.setBackground(new java.awt.Color(204, 153, 0));

        jTxt_DisplayCD_DVD.setColumns(20);
        jTxt_DisplayCD_DVD.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jTxt_DisplayCD_DVD.setRows(5);
        jScrollPane1.setViewportView(jTxt_DisplayCD_DVD);

        javax.swing.GroupLayout cdCoverLayout = new javax.swing.GroupLayout(cdCover);
        cdCover.setLayout(cdCoverLayout);
        cdCoverLayout.setHorizontalGroup(
            cdCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdCoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        cdCoverLayout.setVerticalGroup(
            cdCoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdCoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KennyG_TheMoment.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LeroyAnderson_OrchestralMusic#3.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Copin_PianoConcertoN1Larghetto.jpg"))); // NOI18N
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<< Select on a Title ");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout cdTabLayout = new javax.swing.GroupLayout(cdTab);
        cdTab.setLayout(cdTabLayout);
        cdTabLayout.setHorizontalGroup(
            cdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(cdTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cdCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        cdTabLayout.setVerticalGroup(
            cdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cdTabLayout.createSequentialGroup()
                .addGroup(cdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cdTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cdTabLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, Short.MAX_VALUE)))
                .addGap(121, 121, 121))
        );

        libraryTab.addTab("CD-DVD", new javax.swing.ImageIcon(getClass().getResource("/Image/icon_cd.png")), cdTab); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libraryTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libraryTab, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jTxt_DisplayCD_DVD.setText(null);        
        final URL soundFileURL = this.getClass().getResource("/Sound/01 KENNY G Northern Lights.wav");
        final Inventory inv;
        try {
            this.jTxt_DisplayCD_DVD.setText(null);
            inv = new Inventory(new AudioVisualMaterial(
                    "KENNY G",
                    "Northern Lights",
                    new BigDecimal("2.99"),
                    (short)1996,
                    AudioVisualMaterial.AudioVisualType.CD,
                    new ImageIcon(),
                    AudioVisualMaterial.getSoundClip(soundFileURL)
            ));
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayCD_DVD.setText(intro+inv.getLibraryMaterial().displayInfo());
            try{
                ((AudioVisualMaterial) inv.getLibraryMaterial()).playSoundClip(soundFileURL, 10);
                } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                  Logger.getLogger(Unit8_OOPLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        } catch (IOException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }             
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.jTxt_DisplayCD_DVD.setText(null);
        final URL soundFileURL = this.getClass().getResource("/Sound/02 ANDERSON Plink, Plank, Plunk!.wav");
        final Inventory inv;
        try {
            inv = new Inventory(new AudioVisualMaterial(
                    "LEROY ANDERSON",
                    "Plink, Plank, Plunk!",
                    new BigDecimal("3.99"),
                    (short)1951,
                    AudioVisualMaterial.AudioVisualType.CD,
                    new ImageIcon(),
                    AudioVisualMaterial.getSoundClip(soundFileURL)
            ));
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayCD_DVD.setText(intro+inv.getLibraryMaterial().displayInfo());
            try{
                ((AudioVisualMaterial) inv.getLibraryMaterial()).playSoundClip(soundFileURL, 10);
                } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                  Logger.getLogger(Unit8_OOPLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        } catch (IOException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jTxt_DisplayCD_DVD.setText(null);
        final URL soundFileURL = this.getClass().getResource("/Sound/03 CHOPIN Piano Concerto No 1 - Larghetto.wav");
        final Inventory inv;
        try {
            inv = new Inventory(new AudioVisualMaterial(
                    "CHOPIN",
                    "Piano Concerto No 1 - Larghetto",
                    new BigDecimal("5.94"),
                    (short)1830,
                    AudioVisualMaterial.AudioVisualType.CD,
                    new ImageIcon(),
                    AudioVisualMaterial.getSoundClip(soundFileURL)
            ));
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayCD_DVD.setText(intro+inv.getLibraryMaterial().displayInfo());
            try{
                ((AudioVisualMaterial) inv.getLibraryMaterial()).playSoundClip(soundFileURL, 10);
                } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                  Logger.getLogger(Unit8_OOPLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        } catch (IOException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        final Inventory inv;
        try {
            inv = new Inventory(new Book(
                    "JOSEPH M./ DEFEO JURAN",
                    "Juran's Quality Handbook\n         The Complete Guide to Performance",
                    new BigDecimal("163.64"),
                    (short)2010,
                    BookCoverType.H,
                    Byte.parseByte("6"),
                    1113,
                    new ImageIcon()
            ));            
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayBook.setText(introBook+inv.getLibraryMaterial().displayInfo());
        
        } catch(NumberFormatException ex){
             Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final Inventory inv;
        try {
            inv = new Inventory(new Book(
                    "PAUL/ DEITEL DIETEL",
                    "Java\n          How To Program Early Objects",
                    new BigDecimal("173.78"),
                    (short)2011,
                    BookCoverType.P,
                    Byte.parseByte("9"),
                    1496,
                    new ImageIcon()
            ));            
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayBook.setText(introBook+inv.getLibraryMaterial().displayInfo());
        
        } catch(NumberFormatException ex){
             Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final Inventory inv;
        try {
            inv = new Inventory(new Book(
                    "J. R. R. TOLKIEN",
                    "The Lord of the Rings\n          Omnibus",
                    new BigDecimal("25.07"),
                    (short)2005,
                    BookCoverType.L,
                    Byte.parseByte("50"),
                    1178,
                    new ImageIcon()
            ));            
            
            System.out.print(inv.getLibraryMaterial().displayInfo());
            this.jTxt_DisplayBook.setText(introBook+inv.getLibraryMaterial().displayInfo());
        
        } catch(NumberFormatException ex){
             Logger.getLogger(LibraryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookCover;
    private javax.swing.JPanel bookTab;
    private javax.swing.JPanel cdCover;
    private javax.swing.JPanel cdTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTxt_DisplayBook;
    private javax.swing.JTextArea jTxt_DisplayCD_DVD;
    private javax.swing.JTabbedPane libraryTab;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setTitle("G1 LIBRARY");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(690, 680);           // Size the JFrame to a known size configuration
        this.setLocationRelativeTo(null); // Brings the window to the Center of the screen
        this.setVisible(true);            // Vital allow visibility of the JFrame NB: JFrame.show() is deprecated  }
    }
}
